[package]
name = "log_x"
repository = "https://github.com/icsboyx/log_x"
description = "The `Log X` library provides a flexible and extensible logging framework for Rust applications. It supports different log levels, module-specific logging, and customizable log output formats."
version = "0.1.2"
edition = "2021"
license = "MIT"

[dependencies]
